### ISSUE TITLE
sliders don't show properly in firefox (at least on Linux)

### ISSUE THREAD

**Issue by dpshelio** [alan-turing-institute/science-gateway-inputs#28] opened 2017-08-15 13:46 UTC
Sliders work in the [demo page](http://ionden.com/a/plugins/ion.rangeSlider/demo_interactions.html) using firefox

**Comment by myyong** [comment] 2017-08-15 15:19
It works in updated Chrome now 🗡

**Comment by klapaukh** [comment] 2017-08-17 13:14
I think this is caused by an out dated version of webpack. This seems fixed in the theejs branch (threejs doesn't work with old webpack either).

**Comment by masonlr** [comment] 2017-08-24 10:51
@klapaukh has this now been merged in master. Can we close this issue?

**Comment by klapaukh** [comment] 2017-08-24 10:53
More people should check that this is now fixed. Then it can be closed.

**Closed** 2017-09-18 14:53 UTC
